# Generated by Django 3.2.16 on 2024-06-02 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20240310_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_end',
            field=models.DateField(default=datetime.date(2024, 6, 2)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_start',
            field=models.DateField(default=datetime.date(2024, 6, 2)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='day_of_week_end',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='day_of_week_start',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
